# YOUR NAME OR TITLE OF YOUR SITE
name: Lux Air 365

# YOUR BRAND/PERSONAL TAGLINE
tagline: '<p><span>FLY LUXURY FOR LESS ✈️</span><span>✂️ Discounts for flights up to -50%</span><span>Business & First class</span></p>'

# YOUR/BRAND IMAGE URL
Image_URL: assets/images/luxair_logo_new.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: assets/images/background.jpg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # TELEGRAM
  - Name: Book by Telegram
    URL: https://t.me
    Username: LuxAir365
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # WHATSAPP
  - Name: Book by WhatsApp
    URL: https://wa.me
    Username: '+971585175264'
    Color: '#25d366'
    Icon-Class: fab fa-whatsapp

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
